// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Dom from "@testing-library/dom";
import * as React$1 from "@testing-library/react";
import * as PageTournamentList$Coronate from "../src/PageTournamentList.bs.js";

require("@testing-library/jest-dom");

test("Creating a new tournament works", (function () {
        var page = React$1.render(React.createElement(PageTournamentList$Coronate.make, {}));
        Dom.fireEvent.click(page.getByText(({
                    NAME: "RegExp",
                    VAL: /add tournament/i
                  }).VAL));
        Dom.fireEvent.change(page.getByLabelText(({
                    NAME: "RegExp",
                    VAL: /name:/i
                  }).VAL), {
              target: {
                value: "Deep 13 Open"
              }
            });
        Dom.fireEvent.click(page.getByText(({
                    NAME: "RegExp",
                    VAL: /create/i
                  }).VAL));
        expect(page.getByLabelText("Delete “Deep 13 Open”")).toBeInTheDocument();
      }));

test("Deleting a tournament works", (function () {
        var page = React$1.render(React.createElement(PageTournamentList$Coronate.make, {}));
        Dom.fireEvent.click(page.getByLabelText("Delete “Simple Pairing”"));
        expect(page.queryByText(({
                      NAME: "RegExp",
                      VAL: /simple pairing/
                    }).VAL)).toBe(null);
      }));

export {
  
}
/*  Not a pure module */
