// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as TestData$Coronate from "../src/testdata/TestData.bs.js";
import * as React$1 from "@testing-library/react";
import * as LoadTournament$Coronate from "../src/PageTournament/LoadTournament.bs.js";
import * as PageTourneyPlayers$Coronate from "../src/PageTournament/PageTourneyPlayers.bs.js";

test("Deleted players do not crash the bye queue.", (function () {
        var page = function (param) {
          return React$1.render(React.createElement(LoadTournament$Coronate.make, {
                          children: (function (tournament) {
                              return React.createElement(PageTourneyPlayers$Coronate.make, {
                                          tournament: tournament
                                        });
                            }),
                          tourneyId: TestData$Coronate.deletedPlayerTourney.id
                        }));
        };
        expect(page).not.toThrow();
      }));

export {
  
}
/*  Not a pure module */
