// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Utils$Coronate from "../src/Utils.bs.js";
import * as React$1 from "@testing-library/react";

require("@testing-library/jest-dom");

var date = new Date("2000-01-01T13:55:02.573Z");

test("Date format component works", (function () {
        expect(React$1.render(React.createElement(Utils$Coronate.DateFormat.make, {
                          date: date
                        })).getByText("Jan 01, 2000")).toBeInTheDocument();
      }));

test("Date + time format component works", (function () {
        expect(React$1.render(React.createElement(Utils$Coronate.DateTimeFormat.make, {
                          date: date,
                          timeZone: "America/New_York"
                        })).getByText("Jan 01, 2000, 08:55 AM")).toBeInTheDocument();
      }));

export {
  
}
/*  Not a pure module */
